const canvas=document.getElementById("world"),ctx=canvas.getContext("2d"),$=s=>document.querySelector(s);
let W=innerWidth,H=innerHeight,DPR=Math.min(devicePixelRatio||1,2),started=false,last=0,keys={},time=0;
const world={w:3000,h:1800},state={items:[],flags:{},player:{x:1500,y:1320},energy:100};
const places=[
{id:"cafe",name:"NET CAFE",x:380,y:360,w:480,h:290,c:"#173847",r:"#2d657b"},
{id:"radio",name:"COAST FM",x:1130,y:220,w:380,h:250,c:"#293a3d",r:"#4c6768"},
{id:"arcade",name:"ARCADE",x:2050,y:350,w:430,h:280,c:"#35283e",r:"#684777"},
{id:"cinema",name:"CINEMA",x:350,y:1080,w:520,h:280,c:"#40332d",r:"#725444"},
{id:"house",name:"HOUSE 17",x:2070,y:1100,w:430,h:300,c:"#29382e",r:"#4b614e"}
];
const objects=[
{x:980,y:740,type:"car",label:"ABANDONED TAXI"},{x:1470,y:720,type:"bus",label:"NIGHT BUS"},
{x:1840,y:850,type:"vending",label:"VENDING MACHINE"},{x:1050,y:1040,type:"phone",label:"PAYPHONE"},
{x:2600,y:760,type:"dumpster",label:"DUMPSTER"},{x:1330,y:520,type:"bench",label:"BUS STOP"},
{x:1760,y:1210,type:"bike",label:"BICYCLE"},{x:700,y:820,type:"poster",label:"MISSING POSTER"}
];
const npcs=[{x:920,y:620,tx:920,ty:620,skin:"#a97863",shirt:"#263b4b",name:"THE MAN"},{x:1540,y:820,tx:1540,ty:820,skin:"#9b705d",shirt:"#45364b",name:"THE GIRL"},{x:1850,y:680,tx:1850,ty:680,skin:"#a77c67",shirt:"#304a3e",name:"DELIVERY BOY"},{x:2700,y:940,tx:2700,ty:940,skin:"#9b705d",shirt:"#4a302c",name:"STRANGER"}];
let rain=Array.from({length:220},(_,i)=>({x:(i*137)%world.w,y:(i*79)%world.h,s:8+(i%7)}));
function resize(){W=innerWidth;H=innerHeight;canvas.width=W*DPR;canvas.height=H*DPR;ctx.setTransform(DPR,0,0,DPR,0,0)}addEventListener("resize",resize);resize();
function load(){try{let s=JSON.parse(localStorage.getItem("dgt-save")||"null");if(s)Object.assign(state,s)}catch(e){}}function save(){localStorage.setItem("dgt-save",JSON.stringify(state))}
function notify(t){let el=$("#toast");el.textContent=t;el.classList.add("show");clearTimeout(notify.t);notify.t=setTimeout(()=>el.classList.remove("show"),2200)}
function addItem(x){if(!state.items.includes(x)){state.items.push(x);$("#items").innerHTML=state.items.map(i=>'<span class="item">'+i+"</span>").join("");save();notify("ACQUIRED // "+x)}}
function objective(x){$("#objective").textContent="OBJECTIVE: "+x}
function cam(){return{x:Math.max(0,Math.min(world.w-W,state.player.x-W/2)),y:Math.max(0,Math.min(world.h-H,state.player.y-H/2))}}
function start(){if(started)return;started=true;$("#boot").style.opacity=0;setTimeout(()=>$("#boot").remove(),700);$("#game").hidden=false;load();$("#items").innerHTML=state.items.map(i=>'<span class="item">'+i+"</span>").join("");notify("SIGNAL ACQUIRED // 03:17");requestAnimationFrame(loop)}
$("#startBtn").onclick=start;$("#startBtn").ontouchend=e=>{e.preventDefault();start()};
$("#closePanel").onclick=()=>{$("#panel").classList.remove("open")};
function panel(title,sub,body,action){$("#panelContent").innerHTML='<div class="loc">'+sub+'</div><div class="panel-title">'+title+'</div>'+body+(action?'<button class="action" id="action">'+action+'</button>':"");$("#panel").classList.add("open")}
function interactPlace(id){if(id==="cafe"){addItem("BLACK KEY");objective("FIND THE BRASS TOKEN");panel("THE GHOST DIRECTORY","NET CAFE / NODE 17",'<div class="terminal">CRT STATUS: ONLINE\nUSER: GHOST_17\n\n"IF YOU FOUND THIS, THE TOWN IS STILL RUNNING."\n\nA black key was hidden beneath the desk.</div>')}else if(id==="arcade"){panel("CABINET 04","ARCADE / POWER GRID",'<div class="terminal">HIGH SCORE: 0317\nPLAYER: UNKNOWN\n\nThe machine accepts one code.</div><input id="code" class="input" maxlength="4" inputmode="numeric" placeholder="ENTER CODE">',"UNLOCK CABINET");$("#action").onclick=()=>{if($("#code").value==="0317"){addItem("BRASS TOKEN");objective("RETURN TO HOUSE 17");panel("ACCESS GRANTED","ARCADE / CABINET 04",'<div class="terminal">A brass token drops from the machine.\n\n17 / 08 / 14</div>')}else notify("ACCESS DENIED")}}else if(id==="radio"){notify("STATIC: HOUSE 17...");objective("CHECK THE CINEMA")}else if(id==="cinema"){addItem("FILM TICKET");objective("OPEN HOUSE 17");panel("SEAT 17","CINEMA / SCREEN 02",'<div class="terminal">FRAME 001 — OLD COAST ROAD\nFRAME 002 — NET CAFE\nFRAME 003 — YOU\n\nThe projector knows where you are.</div>')}else if(id==="house"){if(state.items.includes("BLACK KEY")&&state.items.includes("BRASS TOKEN"))panel("THE DOOR OPENS","HOUSE 17 / ENTRY",'<div class="terminal">WELCOME BACK, GHOST_17.\n\nENDING 01\nTHE TOWN IS STILL ONLINE.</div>');else notify("THE DOOR REQUIRES THE KEY + TOKEN")}}
function nearest(){let best=null,d=160;for(const p of places){let q=Math.hypot(state.player.x-(p.x+p.w/2),state.player.y-(p.y+p.h/2));if(q<d){d=q;best={kind:"place",id:p.id,name:p.name}}}for(const o of objects){let q=Math.hypot(state.player.x-o.x,state.player.y-o.y);if(q<d){d=q;best={kind:"object",obj:o,name:o.label}}}return best}
function useObject(o){state.flags[o.type]=true;save();if(o.type==="phone"){panel("PAYPHONE","OLD COAST ROAD",'<div class="terminal">LINE 03\n\n...ring...\n\n"YOU SHOULD NOT BE HERE."\n\nThe line goes dead.</div>');objective("FIND HOUSE 17")}else if(o.type==="vending"){notify("THE VENDING MACHINE RETURNS A BLACK TOKEN");addItem("OLD TOKEN")}else if(o.type==="car"){notify("THE TAXI RADIO IS STILL PLAYING");objective("FOLLOW THE RADIO SIGNAL")}else if(o.type==="poster"){panel("MISSING","WALL POSTER",'<div class="terminal">MISSING\n\nGHOST_17\nLAST SEEN: 03:17\n\nThe photograph looks exactly like you.</div>')}else notify(o.label+" // NOTHING HAPPENS")}
function move(dx,dy){if($("#panel").classList.contains("open"))return;const sp=4.2;let nx=state.player.x+dx*sp,ny=state.player.y+dy*sp;nx=Math.max(35,Math.min(world.w-35,nx));ny=Math.max(100,Math.min(world.h-35,ny));for(const p of places){if(nx>p.x-25&&nx<p.x+p.w+25&&ny>p.y-25&&ny<p.y+p.h+25)return}state.player.x=nx;state.player.y=ny}
function road(){ctx.fillStyle="#11191d";ctx.fillRect(0,650,world.w,190);ctx.fillRect(1320,0,210,world.h);ctx.fillStyle="#263136";for(let x=0;x<world.w;x+=100)ctx.fillRect(x,740,52,5);for(let y=0;y<world.h;y+=100)ctx.fillRect(1418,y,5,52)}
function building(p,t){ctx.fillStyle="#0009";ctx.fillRect(p.x+20,p.y+25,p.w,p.h);ctx.fillStyle=p.r;ctx.fillRect(p.x-15,p.y-32,p.w+30,42);ctx.fillStyle=p.c;ctx.fillRect(p.x,p.y,p.w,p.h);ctx.strokeStyle="#58727b";ctx.lineWidth=2;ctx.strokeRect(p.x,p.y,p.w,p.h);for(let yy=0;yy<2;yy++)for(let xx=0;xx<4;xx++){let wx=p.x+35+xx*(p.w-80)/3,wy=p.y+55+yy*76;ctx.fillStyle=Math.sin(t/650+xx+yy)>.1?"#b9edff":"#122128";ctx.fillRect(wx,wy,38,43)}ctx.fillStyle="#080d10";ctx.fillRect(p.x+p.w/2-34,p.y+p.h-82,68,82);ctx.fillStyle="#b8efff";ctx.font="bold 18px monospace";ctx.fillText(p.name,p.x+20,p.y+p.h+30)}
function drawObject(o,t){let x=o.x,y=o.y;ctx.save();ctx.translate(x,y);ctx.fillStyle="#0008";ctx.beginPath();ctx.ellipse(0,35,42,12,0,0,Math.PI*2);ctx.fill();if(o.type==="car"){ctx.fillStyle="#253943";ctx.fillRect(-55,-20,110,48);ctx.fillStyle="#111c21";ctx.fillRect(-40,-38,78,28);ctx.fillStyle="#8edfff";ctx.fillRect(-32,-32,27,18);ctx.fillRect(6,-32,27,18);ctx.fillStyle="#e64e58";ctx.fillRect(43,-5,8,14)}else if(o.type==="bus"){ctx.fillStyle="#34464b";ctx.fillRect(-55,-35,110,70);ctx.fillStyle="#152329";for(let i=-42;i<45;i+=25)ctx.fillRect(i,-24,18,22)}else if(o.type==="vending"){ctx.fillStyle="#24495a";ctx.fillRect(-22,-45,44,82);ctx.fillStyle="#8de6ff";ctx.fillRect(-14,-34,28,38);ctx.fillStyle="#fff";ctx.fillRect(-7,-22,14,3)}else if(o.type==="phone"){ctx.strokeStyle="#384b51";ctx.lineWidth=7;ctx.beginPath();ctx.moveTo(0,35);ctx.lineTo(0,-45);ctx.stroke();ctx.fillStyle="#8be4ff";ctx.fillRect(-15,-52,30,18)}else if(o.type==="dumpster"){ctx.fillStyle="#24362f";ctx.fillRect(-42,-28,84,45);ctx.fillStyle="#40564c";ctx.fillRect(-47,-35,94,10)}else if(o.type==="bench"){ctx.fillStyle="#654b37";ctx.fillRect(-45,-12,90,10);ctx.fillRect(-40,5,8,30);ctx.fillRect(32,5,8,30)}else if(o.type==="bike"){ctx.strokeStyle="#7da5ae";ctx.lineWidth=3;for(let q of[-20,20]){ctx.beginPath();ctx.arc(q,15,18,0,Math.PI*2);ctx.stroke()}ctx.beginPath();ctx.moveTo(-20,15);ctx.lineTo(0,-18);ctx.lineTo(20,15);ctx.lineTo(-20,15);ctx.stroke()}else{ctx.fillStyle="#8b3038";ctx.fillRect(-45,-55,90,70);ctx.fillStyle="#f2d6bd";ctx.font="bold 10px monospace";ctx.fillText("MISSING", -29,-30);ctx.fillText("GHOST_17",-32,-10)}ctx.restore()}
function npc(n,t){if(Math.hypot(n.tx-n.x,n.ty-n.y)<5){n.tx=600+Math.random()*2100;n.ty=560+Math.random()*850}let a=Math.atan2(n.ty-n.y,n.tx-n.x);n.x+=Math.cos(a)*.35;n.y+=Math.sin(a)*.35;let bob=Math.sin(t/180+n.x)*2;ctx.fillStyle="#0008";ctx.beginPath();ctx.ellipse(n.x,n.y+37,22,8,0,0,Math.PI*2);ctx.fill();ctx.fillStyle=n.shirt;ctx.fillRect(n.x-14,n.y-4+bob,28,40);ctx.fillStyle=n.skin;ctx.beginPath();ctx.arc(n.x,n.y-20+bob,14,0,Math.PI*2);ctx.fill();ctx.fillStyle="#111";ctx.fillRect(n.x-14,n.y-31+bob,28,8);ctx.fillStyle="#d6f5ff";ctx.fillRect(n.x-7,n.y-21+bob,4,3);ctx.fillRect(n.x+4,n.y-21+bob,4,3)}
function player(t){let p=state.player,b=Math.sin(t/110)*2;ctx.fillStyle="#000a";ctx.beginPath();ctx.ellipse(p.x,p.y+40,27,10,0,0,Math.PI*2);ctx.fill();ctx.fillStyle="#0c2938";ctx.fillRect(p.x-16,p.y-2+b,32,42);ctx.fillStyle="#b88770";ctx.beginPath();ctx.arc(p.x,p.y-20+b,16,0,Math.PI*2);ctx.fill();ctx.fillStyle="#0a0c0e";ctx.beginPath();ctx.arc(p.x,p.y-25+b,17,Math.PI,Math.PI*2);ctx.fill();ctx.fillStyle="#7ee8ff";ctx.fillRect(p.x-9,p.y-22+b,5,3);ctx.fillRect(p.x+4,p.y-22+b,5,3);ctx.strokeStyle="#80e4ff";ctx.beginPath();ctx.arc(p.x,p.y-2+b,27,0,Math.PI*2);ctx.stroke()}
function draw(t){let c=cam();ctx.clearRect(0,0,W,H);ctx.save();ctx.translate(-c.x,-c.y);ctx.fillStyle="#081218";ctx.fillRect(0,0,world.w,world.h);road();ctx.fillStyle="#0b1820";ctx.fillRect(0,0,world.w,650);ctx.fillStyle="#d8e8e4";ctx.shadowColor="#9ceaff";ctx.shadowBlur=65;ctx.beginPath();ctx.arc(2450,180,78,0,Math.PI*2);ctx.fill();ctx.shadowBlur=0;for(let i=0;i<40;i++){let x=(i*177)%world.w,y=90+(i*113)%500;ctx.fillStyle="#ffffffaa";ctx.fillRect(x,y,2,2)}places.forEach(p=>building(p,t));objects.forEach(o=>drawObject(o,t));npcs.forEach(n=>npc(n,t));player(t);ctx.strokeStyle="#bcecff22";for(const r of rain){r.y+=r.s*.8;r.x-=2;if(r.y>world.h)r.y=0;ctx.beginPath();ctx.moveTo(r.x,r.y);ctx.lineTo(r.x-7,r.y+25);ctx.stroke()}ctx.restore();ctx.fillStyle="#b9eaff08";ctx.fillRect(0,0,W,H)}
function loop(t){time=t;let dx=(keys.d||keys.ArrowRight?1:0)-(keys.a||keys.ArrowLeft?1:0),dy=(keys.s||keys.ArrowDown?1:0)-(keys.w||keys.ArrowUp?1:0);if(dx||dy){let l=Math.hypot(dx,dy);move(dx/l,dy/l)}draw(t);let n=nearest();if(n){$("#interact").textContent="ENTER / "+n.name;$("#interact").classList.add("show")}else $("#interact").classList.remove("show");requestAnimationFrame(loop)}
addEventListener("keydown",e=>{keys[e.key]=true;if(e.key==="Enter"||e.key==="e"){let n=nearest();if(n)n.kind==="place"?interactPlace(n.id):useObject(n.obj)}if(e.key==="Escape")$("#panel").classList.remove("open")});addEventListener("keyup",e=>keys[e.key]=false);
document.querySelectorAll("#touchpad button").forEach(b=>{let d=b.dataset.dir,iv;function on(){if(d==="up")keys.ArrowUp=true;if(d==="down")keys.ArrowDown=true;if(d==="left")keys.ArrowLeft=true;if(d==="right")keys.ArrowRight=true}function off(){keys.ArrowUp=keys.ArrowDown=keys.ArrowLeft=keys.ArrowRight=false;clearInterval(iv)}b.onpointerdown=e=>{e.preventDefault();on();iv=setInterval(on,50)};b.onpointerup=off;b.onpointercancel=off});
canvas.addEventListener("pointerdown",e=>{if(e.pointerType==="touch"){let r=canvas.getBoundingClientRect(),c=cam(),x=e.clientX-r.left+c.x,y=e.clientY-r.top+c.y,a=Math.atan2(y-state.player.y,x-state.player.x);move(Math.cos(a),Math.sin(a))}});
load();